### ISSUE TITLE
Implement websocket client `WsClient`

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s-curl#55]
- https://curl.se/docs/websocket.html
- https://curl.se/libcurl/c/curl_ws_recv.html
- https://curl.se/libcurl/c/curl_ws_send.html
- https://curl.se/libcurl/c/curl_ws_meta.html

**Comment by hnaderi** [comment]
Is anyone working on it? I think I can give it a try this week.

**Comment by armanbilge** [comment]
Great!

**Comment by hnaderi** [comment]
I've implemented this in the linked PR, however there are some issues which I think are related to libcurl itself, and I've [submitted an issue](https://github.com/curl/curl/issues/10339) for in the curl repository.
