### ISSUE TITLE
`curl_easy_pause: 43` in latest libcurl

### ISSUE THREAD

**Issue by LeeTibbert** [http4s/http4s-curl#6]
_Original title_: Test fails building from source on Ubuntu 22.04, X86_64 

This issue to capture my experience whilst debugging another problem.  I report it in case others try
to build from source.   

I cloned this repository and build it, having make sure I am using the `libcurl4-openssl-dev` used in this CI.
When I do `sbt test`, the executable runs, but I get two instances of ` curl_easy_pause: 43`: one for 'get' and
one for 'put'.

---

_Additional notes from @armanbilge_

- this seems to be due to a change since libcurl 7.68.0, which is currently used in CI and what I developed against.
    https://github.com/http4s/http4s-curl/pull/8#issuecomment-1225072304
- it is also reproducible in macOS
    https://github.com/http4s/http4s-curl/pull/5#issuecomment-1225159297

**Comment by LeeTibbert** [comment]
I believe I did a private project using the artifacts and it worked.  The Dad jokes were a chuckle.

**Comment by LeeTibbert** [comment]
Every new class of user reveals a new set of bugs...

**Comment by armanbilge** [comment]
Thanks for the report. I was able to reproduce in https://github.com/http4s/http4s-curl/pull/8.
